### ISSUE TITLE
Qs being monitored include QAlias objects?

### ISSUE THREAD

**Issue by ghantasalar** [Appdynamics/websphere-mq-monitoring-extension#1]
Hello,
When we instrument AppD WMQ Extension to monitor a QM, the machine agent is throwing 2045 (=MQRC_OPTION_NOT_VALID_FOR_TYPE). We see this on the error log for machine-agent (there is no time stamp in this log). It seems to be coming at the point where the agent is processing the QDepth from a QAlias object (Q filter used is INCLUDE=\* - basically get the Qdepths for all local Qs is the intent). Any thoughts as to how this can be avoided? Listing the Qs explicitly is an option - but shouldn't the WMQ Extension be avoiding reading the Qdepth from a QAlias (it should read curdepth only for local Qs and avoid all other Q-types...)?

Thanks
-rg

**Comment by BalakrishnaV** [comment]
Hi @ghantasalar,

There were fixes and enhancements to this extension since the issue was raised. We are closing this issue now. Please feel free to open a new one if the problem still persists.

Thanks
