### ISSUE TITLE
Question about ServerConn-Channel keepalive in client mode

### ISSUE THREAD

**Issue by Huang-Lee** [Appdynamics/websphere-mq-monitoring-extension#10]
Hello
I have the Appdynamics MQ-Extension running in client mode. It connects once per minute to the Queue-Manager, creates a serverconn-channel-instance, grabs the MQ-metrics and then stops the channel-instance.
My question is: Is there a way to keep it from stopping the channel-instance so that the channel stays active?
Thanks!

**Comment by BalakrishnaV** [comment]
Hi Huang Lee,
Extension doesn't create a channel instance, it just establishes the connection using the specified channel. 
Hope this answers your question. In case of further questions, we would suggest raising a support request by emailing to help@appdynamics.com.

Thanks
