### ISSUE TITLE
Limitation on number of QMs that can be monitored by WMQ extension?

### ISSUE THREAD

**Issue by ghantasalar** [Appdynamics/websphere-mq-monitoring-extension#2]
Hello,
We have setup the machine-agent to be started with maxMachineMetrics=400000 (400K) (see below the invokation command for starting the machine agent). 
nohup /opt/isv/appd/ma/bin/machine-agent -Dappdynamics.machine.agent.maxMachineMetrics=400000 &

Here is our test scenario:
1. machine-agent (ma) is remote to the QMs, configured to connect to the QMs using Client chls (transport set to CLIENT-MODE)
2. 4 QMs are being monitored
3. Each QM has a few hundred Qs and few hundred Channels
4. Q & Chl filter = INCLUDE=\* (basically monitor all Qs for Qdepth & Chl statuses)

Here is the observation:
1. The nohup.out that gets the errors thrown by machine-agent (see the invokation command above) throws 2017 (MQRC_HANDLE_NOT_AVAILABLE). We figured this is due to fact the Max Handles on the QM by default is 256 and since we have a large Qs & Chls, this error is coming. We have since specified only Qs (Q filter is INCLUDE=_)and removed chls from monitoring (Chl filter EXCLUDE=_). This got us the desired stats for the Qs. However, one QM was not being reported. 
1. We next restricted the # of Qs being monitored further - specifying only a handful of Qs. This is when all 4 QMs showed up in the Controller. 
2. Not all Qs have all Attributes reported - this probably again is due to the buffer space limitation...

Question now is - what are the limitations governing the machine-agent configs? How can we comfortably monitor **all** Qs and Chls on all QMs? Does this require a huge buffer maxMachineMetrics ?If yes, what is the server parameter we need to tweak ? Should we divide and conquer (one ma polling only Qs and another only polling Chls?) Can I run multiple agents concurrently each gathering and reporting only a sub-set of information (for example - 4 machine agents - each polling x number of Qs or Chls etc) What are the limitations with this approach? 
1. Previously reported an issue with 2017 (MQRC_HANDLE_NOT_AVAILABLE) that was being reported in the nohup.out by machine-agent. Can we review the code to see there is no "leakage" of handles by the websphere-mq extension?

**Comment by BalakrishnaV** [comment]
Hi @ghantasalar,

There were fixes and enhancements to this extension since the issue was raised. We are closing this issue now. Please feel free to open a new one if the problem still persists.

Thanks
