### ISSUE TITLE
How to configure SSL Cipher Suite?

### ISSUE THREAD

**Issue by Huang-Lee** [Appdynamics/websphere-mq-monitoring-extension#9]
Hello!
I'd like to use the AppDynamics MQ Extension in Client mode with a ServerConn with SSL. The Readme says "Configure the IBM SSL Cipher Suite in the config.yaml", but it doesn't explain what parameters to use or how to do it. Is it documented somewhere?
Thanks!

**Comment by kunalgupApDx** [comment]
If you check the config.yaml, there is a field called cipherSuite

# IBM Cipher Suite e.g. "SSL_RSA_WITH_AES_128_CBC_SHA256"..
# For translation to IBM Cipher http://www.ibm.com/support/knowledgecenter/SSFKSJ_8.0.0/com.ibm.mq.dev.doc/q113210_.htm
#cipherSuite: ""

Please make sure you follow the other instructions on SSL in the readme. 
@BalakrishnaV

**Comment by Huang-Lee** [comment]
Ah, you're right, the parameter "cipherSuite" is in the config.yaml, I hadn't seen it at first. Thank you!
